### ISSUE TITLE
Request to Add Project to Review Jam: Flowrunner-canvas

### ISSUE THREAD

**Issue by devhelpr** [marianoguerra/marianoguerra.github.io#3]
Project Name: Flowrunner-canvas

Project Description: Flowrunner-canvas is a flow based programming environment that can be used standalone but also very easily be added to an existent frontend javascript/typescript toolchain. When used standalone it can be used without writing code, but it is extendable in various ways depending on your needs. It includes a basic layout editor to create a UI out of a flow. 

Project URL: https://github.com/devhelpr/flowrunner-canvas

Project Task : Create a BMI calculator using a FormTask node, an ExpressionTask and DebugTask nodes (BMI formula : weight/height*height)

Which feedback do I want: The project is still in a very experimental stage, a lot of of basic UI elements and interactions needed for visual flow editing are not there yet. But I do wonder how you like the editing of node properties directly on the canvas in comparison with editing node properties via a property editor in a sidebar.

**Comment by marianoguerra** [comment]
added
